@api = http://localhost:4000/api
@token = pegue_aqui_el_token

### Login usuario
POST {{api}}/auth/login
Content-Type: application/json

{
  "email": "cliente@asesoriainmobiliariajb.com",
  "password": "REEMPLAZAR_CON_PASSWORD_LOCAL"
}

### Catálogo público
GET {{api}}/properties

### Mis facturas
GET {{api}}/invoices/me
Authorization: Bearer {{token}}

### Login administrador
POST {{api}}/auth/login
Content-Type: application/json

{
  "email": "admin@asesoriainmobiliariajb.com",
  "password": "REEMPLAZAR_CON_PASSWORD_LOCAL"
}

### Dashboard administrativo
GET {{api}}/admin/dashboard
Authorization: Bearer {{token}}
