apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-configmap.yaml
  - 06-apps.yaml
  - 07-clamav.yaml
  - 08-network-policies.yaml
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
  - target:
      kind: ConfigMap
      name: asesoria-config
    patch: |-
      - op: add
        path: /metadata/labels
        value:
          deployment-phase: config
